version: '2'

services:
  service:
    build:
      context: ./service
    ports: 
      - "2222:2222"
      - "4000:4000"
    env_file: 
      - .env
  crawler:
    build:
      context: .
      dockerfile: Dockerfile-crawler
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    env_file: 
      - .env
  website:
    build:
      context: ./website
    depends_on:
      - service
      - mongo
    ports:
      - "8080:80"
    env_file: 
      - .env
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file: 
      - .env
  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - "8081:8081"
    env_file: 
      - .env
  redis:
    image: redis:latest
    expose:
      - "6379"
    env_file: 
      - .env
