version: '2'

services:
  service:
    build:
      context: ./service
    ports: 
      - "2222:2222"
      - "4000:4000"
  crawler:
    build:
      context: .
      dockerfile: Dockerfile-crawler

    depends_on:
      - mongo
    ports:
      - "5000:5000"
  website:
    build:
      context: ./website
    depends_on:
      - service
      - mongo
    ports:
      - "8080:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - "8081:8081"
  redis:
    image: redis:latest
    expose:
      - "6379"
    # volumes:
    #   - redis_data:/data